### PR TITLE
 Refactored and added tests to Settings

### PR DESCRIPTION
**Pull request by JonnyDeates**
Adds tests for settings.

I haven't been able to find a way to mockout the Obsidian package. I spent awhile trying to get it bundled in, but I realized the only file provided in their Obsidian repo is a type file, not the actual module. So that was not the solution, then I tried creating a mock of the Obsidian repo, I made progress, but it was alot for little output, so I decided that a refactor for the settings and tests with that refactor could be helpful. I still think more test coverage is needed, and I am happy adding them if there is a solid way of getting around the Obsidian package throwing a fit.

I did also check some other repositories, it seems like most places just don't test any of the files that import from Obsidian.
I was looking off this list https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Community+Talks/Plugin+Testing+for+Developers

EDIT: I just closed it, I hadn't rebased off of the master branch in a bit of a while, so this branch should be ready to merge.

### CODE REVIEW

**Comment by JonnyDeates** [comment]
@benr77 I can try to add more tests, the main.ts, would need to be refactored some way some how, and the gitlab-api could have the Obsidian mock file, it does work, its just a headache to include. 

I do TDD for work so I really don't mind adding tests, the annoyance of the obsidian node-module though is something I haven't had to deal with.

**Comment by JonnyDeates** [comment]
I added some more tests. gitlab-api, gitlab-loader, default-template, 

I also added a mocks file for Obsidian to get this working. The untested ones are now 

filesystem.ts
main.ts
settings-tab.ts

**Comment by benr77** [comment]
This all looks good thanks for your efforts. Do you want me to merge it now or do you want to add more tests first?

I have very little free time available at the moment, and there does seem to be some interest in this project, so building up a decent test suite is a priority to allow merging contributions with confidence.

**Comment by JonnyDeates** [comment]
I think it is good to merge in, those last files are a real pain to test, they each require a bunch of obsidian to be mocked, and sub functionality mocked. I could go through, but maybe sometime in the future. I think this branch is ready for what it is. Still those three files remain untested. Hopefully Obsidian creates a testing-module that does a lot of this headache for developers.

**Pull request merged**
