### PR TITLE
Refresh time full response

### PR DESCRIPTION
**Pull request by JonnyDeates**
Added Option to choose how often the plugin refreshes the Issues
Added Option to turn off pulling issues on startup

Added the full gitlab response to the issue that is retrieved from the api call. This is in response to https://github.com/benr77/obsidian-gitlab-issues/issues/24 .

### CODE REVIEW

**Comment by JonnyDeates** [comment]
This also touches on https://github.com/benr77/obsidian-gitlab-issues/issues/16 , he suggested the idea of changing the refresh rates, and when issues are pulled, which was the initial purpose of this commit, I personally only want it pulled on start up, and not refreshing every 15.

**Comment by benr77** [comment]
This looks good, thank you. 

Please could you update the screenshot in the README that shows the new config settings.

Secondly, the project is desperate for test coverage, but I have absolutely no time at the moment. Would you be able to add some tests, to at least cover some of your changes?

**Comment by JonnyDeates** [comment]
I added a few tests, I was having difficulty getting obsidian module in my tests to run, not sure why the bundling of the plugin   . I spent awhile trying to debug it, but no alas. So I added it a few of the components, even googling around didn't help with it. I did see a few other plugin projects that have tests, but after spending that time I figured it would be okay. 

Also here is the image.

**Comment by JonnyDeates** [comment]
Screenshot 2024-05-29 at 1 57 27 PM

**Comment by benr77** [comment]
Thank you for your efforts!

**Pull request merged**
